### ISSUE TITLE
feature:repo-add xxxx . Error executing command: Error resolving artifact 

### ISSUE THREAD

**Issue by RRRlizhen** [steinarb/jersey-demo#1]
karaf@root()> **feature:repo-add** mvn:no.priv.bang.demos.jerseyinkaraf/jerseyinkaraf/LATEST/xml/features
Adding feature url mvn:no.priv.bang.demos.jerseyinkaraf/jerseyinkaraf/LATEST/xml/features

Error executing command: **Error resolving artifact no.priv.bang.demos.jerseyinkaraf:jerseyinkaraf:xml:features:LATEST : mvn:no.priv.bang.demos.jerseyinkaraf/jerseyinkaraf/LATEST/xml/features**

**Comment by steinarb** [comment]
Hm... looks like at the point of writing the README I had planned to release this demo to maven central, but later decided not to (since it's just a demo).

That means that before doing repo-add, you will have to clone and build the demo (it's a very small application) with the following commands:
```
git clone https://github.com/steinarb/jersey-demo.git
cd jersey-demo
mvn clean install
```

I will update the README later today when I have better connectivity.
